baseurl = 'http://ptdewey.github.io/'
languageCode = 'en-us'
title = "Patrick's Portfolio"
author = 'Patrick Dewey'
theme = 'blackburn'

[indexes]
    tag = "tags"
    topic = "topics"

[params]
    # subtitle = "Personal Portfolio"

[menu]
    [[menu.main]]
        name = "Home"
        pre = "<i class='fa fa-home fa-fw'></i>"    
        weight = 1
        identifier = "home"
        url = "/"

    [[menu.main]]
        name = "Resume"
        pre = "<i class='fa fa-list fa-fw'></i>"
        weight = 2
        identifier = "resume"
        url = "/resume/"

    [[menu.main]]
        name = "Projects"
        pre = "<i class='fa fa-code fa-fw'></i>"
        weight = 3
        identifier = "projects"
        url = "/projects/"

    # [[menu.main]]
    #     name = "Contact"
    #     pre = "<i class='fa fa-phone fa-fw'></i>"
    #     weight = 4
    #     identifier = "contact"
    #     url = "/contact/"


[social]
    linkedin = "patricktdewey"
    github = "thesupremetoast"

